const STAGES=['New Lead','Contacted','Follow-Up Due','Meeting Booked','Closed'];
const STORAGE='revops-pipeline-v1';
const seedLeads=[
  {id:'L-101',name:'Aisha Coleman',source:'Instagram',quality:'Hot',stage:'Follow-Up Due',first:'2026-09-19',next:'2026-09-29',owner:'Maya',notes:'Asked about listing promotion and requested pricing.'},
  {id:'L-102',name:'Jordan Blake',source:'ListKit',quality:'Intent',stage:'Contacted',first:'2026-09-21',next:'2026-09-30',owner:'Maya',notes:'Intent lead; waiting on preferred call time.'},
  {id:'L-103',name:'Riley Morgan',source:'Realtor.com SMS',quality:'Warm',stage:'Meeting Booked',first:'2026-09-16',next:'2026-10-02',owner:'David',notes:'Discovery call booked.'},
  {id:'L-104',name:'Chinedu Okafor',source:'Meta Ads',quality:'Cold',stage:'New Lead',first:'2026-09-27',next:'2026-09-30',owner:'David',notes:'New paid-funnel lead.'},
  {id:'L-105',name:'Sofia Grant',source:'Instagram',quality:'Intent',stage:'New Lead',first:'2026-09-28',next:'2026-09-29',owner:'Maya',notes:'Requested case studies in DM.'},
  {id:'L-106',name:'Marcus Lee',source:'ListKit',quality:'Hot',stage:'Contacted',first:'2026-09-18',next:'2026-09-29',owner:'David',notes:'Positive email reply.'},
  {id:'L-107',name:'Tara Williams',source:'Realtor.com SMS',quality:'Warm',stage:'Follow-Up Due',first:'2026-09-22',next:'2026-09-29',owner:'Maya',notes:'Second follow-up due.'},
  {id:'L-108',name:'Noah Bennett',source:'Instagram',quality:'Hot',stage:'Closed',first:'2026-09-09',next:'2026-09-24',owner:'David',notes:'Closed won.'},
  {id:'L-109',name:'Grace Nwosu',source:'ListKit',quality:'Intent',stage:'Follow-Up Due',first:'2026-09-23',next:'2026-09-30',owner:'Maya',notes:'Intent signal detected.'},
  {id:'L-110',name:'Ethan Parker',source:'Meta Ads',quality:'Warm',stage:'Contacted',first:'2026-09-20',next:'2026-10-01',owner:'David',notes:'Requested a callback.'},
  {id:'L-111',name:'Mina Joseph',source:'Instagram',quality:'Cold',stage:'New Lead',first:'2026-09-26',next:'2026-10-03',owner:'Maya',notes:'No response yet.'},
  {id:'L-112',name:'Daniel Price',source:'ListKit',quality:'Ghosted',stage:'Follow-Up Due',first:'2026-09-17',next:'2026-09-29',owner:'David',notes:'No reply after initial contact.'}
];
const campaigns=[
 {name:'ListKit Cold Email (Interested Leads)',status:'Running',working:'Steady replies, automations live, tracking started',automation:'ListKit → Airtable sync, lead tag & timestamp',dashboard:'Airtable dashboard live',tools:'ListKit, Airtable, Gmail, Zapier, Slack optional'},
 {name:'ListKit Intent Leads',status:'Running',working:'Fast lead detection, reminders, auto-notify working',automation:'Auto-tag intent leads, reminder system live',dashboard:'Airtable dashboard live',tools:'ListKit, Airtable, Zapier, Gmail, Slack optional'},
 {name:'Realtor.com SMS',status:'Relaunched',working:'Portal functioning, SMS drip logic ready',automation:'Reminders + logic in place',dashboard:'v0 portal dashboard live',tools:'v0 app, AirDroid'},
 {name:'Meta Ad Campaign',status:'Inactive',working:'Funnel logic mapped, past campaigns reviewed',automation:'Planned',dashboard:'Pending',tools:'Meta Ads, Zapier/n8n/Make, Airtable'},
 {name:'Google PPC Campaign',status:'Inactive',working:'High scalability potential',automation:'Planned',dashboard:'Pending',tools:'Google Ads, Zapier/n8n/Make, Airtable'},
 {name:'Instagram Inbox',status:'Active',working:'VA → BDR handoff working, follow-ups triggered',automation:'Manual entry → reminders live',dashboard:'Airtable Follow-Up board',tools:'Instagram, Airtable, Make'},
 {name:'Social Posting (IG, Pinterest, LinkedIn)',status:'Initial Setup',working:'Fields mapped, logic planned',automation:'Planned (webhook/project data)',dashboard:'Pending',tools:'Airtable, Portal, Make, Buffer/Later'},
 {name:'Customer Email Marketing',status:'Strategy Built',working:'Segments + content plan scoped',automation:'Not yet',dashboard:'Pending',tools:'Airtable, Klaviyo planned, Make'}
];
let leads=load();
function load(){try{const x=JSON.parse(localStorage.getItem(STORAGE));return Array.isArray(x)&&x.length?x:seedLeads.map(x=>({...x}));}catch{return seedLeads.map(x=>({...x}))}}
function save(){localStorage.setItem(STORAGE,JSON.stringify(leads))}
const $=s=>document.querySelector(s), $$=s=>Array.from(document.querySelectorAll(s));
const esc=s=>String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\'':'&#39;','"':'&quot;'}[c]));
function toast(msg){const t=$('#toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),2200)}
function qualityClass(q){return 'q-'+q.toLowerCase().replace(/[^a-z]+/g,'-').replace(/-$/,'')}
function openModal(id){const r=leads.find(x=>x.id===id);if(!r)return;$('#recordId').value=r.id;$('#modalTitle').textContent=r.name;$('#fName').value=r.name;$('#fSource').value=r.source;$('#fQuality').value=r.quality;$('#fStage').innerHTML=STAGES.map(x=>`<option ${x===r.stage?'selected':''}>${x}</option>`).join('');$('#fFirst').value=r.first;$('#fNext').value=r.next;$('#fOwner').value=r.owner;$('#fNotes').value=r.notes||'';$('#recordModal').classList.remove('hidden');setTimeout(()=>$('#fName').focus(),20)}
function closeModal(){$('#recordModal').classList.add('hidden')}
function renderDashboard(){
  const counts=Object.fromEntries(STAGES.map(s=>[s,leads.filter(l=>l.stage===s).length]));
  $('#stageBars').innerHTML=STAGES.map(s=>{const pct=Math.max(8,Math.round((counts[s]/Math.max(leads.length,1))*100));return `<div class="stage-row"><div class="stage-label">${s}</div><div class="bar-track"><div class="bar-fill" style="width:${pct}%"></div></div><div class="stage-count">${counts[s]}</div></div>`}).join('');
  const sourceCounts=['Instagram','Realtor.com SMS','ListKit','Meta Ads'].map(s=>[s,leads.filter(l=>l.source===s).length]);const max=Math.max(...sourceCounts.map(x=>x[1]),1);
  $('#sourceChart').innerHTML=sourceCounts.map(([s,n])=>`<div class="bar-col"><div class="bar-value">${n}</div><div class="bar" style="height:${Math.max(16,(n/max)*170)}px"></div><div class="bar-label">${esc(s)}</div></div>`).join('');
  $('#followupBoard').innerHTML=['New Lead','Contacted','Follow-Up Due','Meeting Booked'].map(stage=>`<div class="kanban-col"><div class="kanban-title"><span>${stage}</span><span class="kanban-count">${leads.filter(l=>l.stage===stage).length}</span></div>${leads.filter(l=>l.stage===stage).slice(0,3).map(l=>`<div class="lead-card" data-id="${l.id}"><div class="lead-name">${esc(l.name)}</div><div class="lead-meta"><span>${esc(l.source)}</span><span class="quality ${qualityClass(l.quality)}">${esc(l.quality)}</span></div><div class="lead-meta"><span>Next: ${l.next}</span><span>${esc(l.owner)}</span></div></div>`).join('')||'<div class="empty">No records</div>'}</div>`).join('');
  $('#campaignTable').innerHTML=campaigns.slice(0,5).map(c=>`<tr><td><strong>${esc(c.name)}</strong></td><td><span class="campaign-status ${c.status.toLowerCase().replace(/\s+/g,'-')}">${esc(c.status)}</span></td><td>${esc(c.automation)}</td><td>${esc(c.dashboard)}</td><td><span class="tool-chip">${esc(c.tools)}</span></td></tr>`).join('');
  $('#kpiLeads').textContent=48;$('#kpiMeetings').textContent=14;
}
function renderPipeline(){
  const sf=$('#statusFilter').value,qf=$('#qualityFilter').value,src=$('#sourceFilter').value;const filtered=leads.filter(l=>(sf==='All'||l.stage===sf)&&(qf==='All'||l.quality===qf)&&(src==='All'||l.source===src));
  $('#pipelineCount').textContent=`${filtered.length} records`;$('#pipelineGrid').innerHTML=STAGES.map(stage=>{const arr=filtered.filter(l=>l.stage===stage);return `<div class="pipeline-col"><h3><span>${stage}</span><span>${arr.length}</span></h3><div class="pipeline-list">${arr.map(l=>`<div class="mini-card" data-id="${l.id}"><div class="lead-name">${esc(l.name)}</div><div class="mini-tags"><span class="quality ${qualityClass(l.quality)}">${esc(l.quality)}</span><span class="mini-date">${l.next}</span></div><div class="lead-meta"><span>${esc(l.source)}</span><span>${esc(l.owner)}</span></div></div>`).join('')||'<div class="empty">No matching records</div>'}</div></div>`}).join('');
}
function renderFollowups(){const due=[...leads].filter(l=>l.stage==='Follow-Up Due').sort((a,b)=>a.next.localeCompare(b.next));$('#followupTable').innerHTML=due.map(l=>`<tr><td><strong>${esc(l.name)}</strong></td><td>${esc(l.source)}</td><td><span class="quality ${qualityClass(l.quality)}">${esc(l.quality)}</span></td><td>${l.next}</td><td>${esc(l.owner)}</td><td>${esc(l.stage)}</td><td><button class="ghost-btn small" data-id="${l.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="7" class="empty">No follow-ups due.</td></tr>'}
function renderCampaigns(){$('#campaignCards').innerHTML=campaigns.map(c=>`<article class="campaign-card"><h3>${esc(c.name)}</h3><div class="campaign-meta"><span class="campaign-status ${c.status.toLowerCase().replace(/\s+/g,'-')}">${esc(c.status)}</span><span class="tool-chip">${esc(c.dashboard)}</span></div><div class="campaign-row"><div class="campaign-field"><span>What’s working</span><strong>${esc(c.working)}</strong></div><div class="campaign-field"><span>Automations</span><strong>${esc(c.automation)}</strong></div></div><div class="campaign-row"><div class="campaign-field"><span>Dashboard</span><strong>${esc(c.dashboard)}</strong></div><div class="campaign-field"><span>Tools / integrations</span><strong>${esc(c.tools)}</strong></div></div></article>`).join('')}
function renderLeads(){const term=$('#searchInput').value.trim().toLowerCase();const rows=leads.filter(l=>!term||Object.values(l).join(' ').toLowerCase().includes(term));$('#leadCount').textContent=`${rows.length} records`;$('#leadTable').innerHTML=rows.map(l=>`<tr><td><strong>${esc(l.name)}</strong><div class="lead-meta">${esc(l.notes||'')}</div></td><td>${esc(l.source)}</td><td><span class="quality ${qualityClass(l.quality)}">${esc(l.quality)}</span></td><td>${esc(l.stage)}</td><td>${l.first}</td><td>${l.next}</td><td>${esc(l.owner)}</td><td><button class="ghost-btn small" data-id="${l.id}">Edit</button></td></tr>`).join('')||'<tr><td colspan="8" class="empty">No matching records.</td></tr>'}
function currentView(name){$$('.view').forEach(v=>v.classList.add('hidden'));$('#'+name+'View').classList.remove('hidden');const title=name[0].toUpperCase()+name.slice(1);$('#pageTitle').textContent=title==='Leads'?'Lead records':title;$('#crumb').textContent=title==='Dashboard'?'Overview':title;$$(('.nav-item[data-view]')).forEach(b=>b.classList.toggle('active',b.dataset.view===name));if(name==='dashboard')renderDashboard();if(name==='pipeline')renderPipeline();if(name==='followups')renderFollowups();if(name==='campaigns')renderCampaigns();if(name==='leads')renderLeads()}
function populateFilters(){$('#statusFilter').innerHTML='<option value="All">All stages</option>'+STAGES.map(x=>`<option>${x}</option>`).join('');$('#sourceFilter').innerHTML='<option value="All">All sources</option>'+['Instagram','Realtor.com SMS','ListKit','Meta Ads'].map(x=>`<option>${x}</option>`).join('')}
function addLead(){const id='L-'+(Math.max(100,...leads.map(x=>parseInt(x.id.slice(2))||100))+1);const today=new Date().toISOString().slice(0,10);leads.unshift({id,name:'New Lead',source:'Instagram',quality:'Intent',stage:'New Lead',first:today,next:today,owner:'Maya',notes:''});save();renderDashboard();openModal(id)}
function exportCSV(){const headers=['id','name','source','quality','stage','first','next','owner','notes'];const lines=[headers.join(','),...leads.map(r=>headers.map(h=>`"${String(r[h]??'').replace(/"/g,'""')}"`).join(','))];const blob=new Blob([lines.join('\n')],{type:'text/csv'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='revops-pipeline-leads.csv';a.click();URL.revokeObjectURL(a.href);toast('CSV exported')}
function exportRecord(){const id=$('#recordId').value,r=leads.find(x=>x.id===id);if(!r)return;const blob=new Blob([JSON.stringify(r,null,2)],{type:'application/json'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`${r.id}-record.json`;a.click();URL.revokeObjectURL(a.href);toast('Record exported')}
function handleEditClick(e){const btn=e.target.closest('[data-id]');if(btn)openModal(btn.dataset.id)}

$('#addLeadBtn').addEventListener('click',addLead);$('#exportCsvBtn').addEventListener('click',exportCSV);$('#closeModal').addEventListener('click',closeModal);$('#cancelBtn').addEventListener('click',closeModal);$('#exportRecordBtn').addEventListener('click',exportRecord);$('#notifyBtn').addEventListener('click',()=>toast('BDR reminder sent'));
$('#recordModal').addEventListener('click',e=>{if(e.target===$('#recordModal'))closeModal()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
$('#leadForm').addEventListener('submit',e=>{e.preventDefault();const id=$('#recordId').value,i=leads.findIndex(x=>x.id===id);if(i<0)return;leads[i]={...leads[i],name:$('#fName').value.trim(),source:$('#fSource').value,quality:$('#fQuality').value,stage:$('#fStage').value,first:$('#fFirst').value,next:$('#fNext').value,owner:$('#fOwner').value.trim(),notes:$('#fNotes').value.trim()};save();closeModal();renderDashboard();renderPipeline();renderFollowups();renderLeads();toast('Changes saved')});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>currentView(b.dataset.view)));
$('#statusFilter').addEventListener('change',renderPipeline);$('#qualityFilter').addEventListener('change',renderPipeline);$('#sourceFilter').addEventListener('change',renderPipeline);$('#searchInput').addEventListener('input',renderLeads);
['#followupBoard','#pipelineGrid','#followupTable','#leadTable'].forEach(sel=>$(sel).addEventListener('click',handleEditClick));
$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>{currentView('pipeline');$('#qualityFilter').value=b.dataset.filter==='Follow-Up Due'?'All':b.dataset.filter;$('#statusFilter').value=b.dataset.filter==='Follow-Up Due'?'Follow-Up Due':'All';renderPipeline()}));
populateFilters();currentView('dashboard');
